<?php

/**
 * @file
 * Install, update and uninstall functions for the DrupalEasy Repositories module.
 */

use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_uninstall().
 */
function drupaleasy_repositories_uninstall() {
  FieldConfig::loadByName('user', 'user', 'field_repository_url')->delete();
  \Drupal::service('messenger')->addStatus('The Repository URL field on the user entity has been deleted.');
}
