drupaleasy_repositories.settings:
  type: config_object
  label: 'DrupalEasy repositories settings'
  mapping:
    repositories:
      type: sequence
      label: 'Repositories'
      sequence:
        type: string
